name: l_x
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  launcher_assist: ^1.1.3
  intl: ^0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: false
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 500
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
